services:
  db:
    image: postgres:15-alpine
    container_name: ibkt_postgres_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ibkt_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ibkt_redis_dev
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data_dev:
